logging:
  level:
    ROOT: INFO
    org.ylzl.eden: DEBUG

spring:
  # 内存数据库
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  # 关系数据库
  datasource:
    # 内存数据源
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: demo
    # 单数据源
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: admin123
#    url: jdbc:mysql://10.2.2.47:5306/demo?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=${spring.application.name}
    # 多数据源，使用 @DS 切换
  #    dynamic:
  #      datasource:
  #        ds1:
  #          username:
  #          password:
  #          url: jdbc:mysql://localhost:3306/ds1?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  #          type: ${spring.datasource.type}
  #          driver-class-name: ${spring.datasource.driver-class-name}
  #        ds2:
  #          username:
  #          password:
  #          url: jdbc:mysql://localhost:3306/ds2?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  #          driver-class-name: ${spring.datasource.driver-class-name}
  #          type: ${spring.datasource.type}
  #      primary: ds1
  #      strict: true
  # 分库分表组件
  #  shardingsphere:
  #    props:
  #      sql.show: true
  #    datasource:
  #      names: demo
  #      demo:
  #        username: ${spring.datasource.dynamic.datasource.demo.username}
  #        password: ${spring.datasource.dynamic.datasource.demo.password}
  #        driver-class-name: ${spring.datasource.dynamic.datasource.demo.driver-class-name}
  #        jdbc-url: ${spring.datasource.dynamic.datasource.demo.url}
  #        type: ${spring.datasource.dynamic.datasource.demo.type}
  #    sharding:
  #      defaultDataSourceName: demo
  cloud:
    sentinel:
      enabled: true
      transport:
        dashboard: localhost:8090
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            groupId: sentinel
            dataId: ${spring.application.name}-flow-rule
            rule-type: flow
            data-type: json
  # 缓存数据库
  redis:
    password: puyiwm
    timeout: 5000
    # 单机
    database: 1
    host: 10.2.2.41
    port: 6379
    # 集群
#    cluster:
#      nodes: 10.2.2.45:6379,10.2.2.48:6379,10.2.2.47:6379,10.2.2.47:6380,10.2.2.47:6381,10.2.2.47:6382
  # 模板引擎
  thymeleaf:
    cache: false
  # 链路跟踪
  zipkin:
    base-url: http://10.2.2.47:9411
  # 链路采集
  kafka:
    bootstrap-servers: 10.2.2.35:9092

# 消息队列
rocketmq:
  name-server: 10.2.2.45:9876;10.2.2.48:9876
  producer:
    group: ${spring.application.name}
#    access-key:
#    secret-key:
  consumer:
    group: ${spring.application.name}
    topic: demo

# 分布式调度平台
#xxl-job:
#  admin:
#    addresses: http://127.0.0.1:8080/xxl-job-admin/
#    access-token:
#  executor:
#    app-name: ${spring.application.name}
#    ip:
#    port: 8080
#    log-path: /data/applogs/xxl-job/jobhandler/
#    log-retention-days: 7

# 实时监控
cat:
  enabled: true
  home: C:\\Users\\sion1\\.cat
  servers: 127.0.0.1
  tcp-port: 2280
  http-port: 8080
